/*
 * Policy Service
 *
 * Service to interact with Policies and related objects.
 *
 * API version: v2.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// RenewalLinkResponseModel struct for RenewalLinkResponseModel
type RenewalLinkResponseModel struct {
	// Description not provided.
	PolicyHolderId string `json:"policyHolderId"`
	// Description not provided.
	ProposalId string `json:"proposalId"`
	// Description not provided.
	RenewalLink string `json:"renewalLink"`
}
