/*
 * Policy Service
 *
 * Service to interact with Policies and related objects.
 *
 * API version: v2.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ConvertQuoteModel struct for ConvertQuoteModel
type ConvertQuoteModel struct {
	Quotes []string `json:"quotes"`
}
