/*
 * Policy Service
 *
 * Service to interact with Policies and related objects.
 *
 * API version: v2.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PolicyHistoryModel struct for PolicyHistoryModel
type PolicyHistoryModel struct {
	// Description not provided.
	HistoryAction string `json:"historyAction"`
	// Description not provided.
	HistoryCreatedBy string `json:"historyCreatedBy"`
	HistoryEntity PolicyModel `json:"historyEntity"`
	// Description not provided.
	HistoryId string `json:"historyId"`
	// Description not provided.
	HistoryTimestamp string `json:"historyTimestamp"`
	// Description not provided.
	HistoryVersion int32 `json:"historyVersion"`
}
