/*
 * Policy Service
 *
 * Service to interact with Policies and related objects.
 *
 * API version: v2.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// TerminatePolicyResponseModel struct for TerminatePolicyResponseModel
type TerminatePolicyResponseModel struct {
	Policy PolicyModel `json:"policy"`
}
