/*
 * Policy Service
 *
 * Service to interact with Policies and related objects.
 *
 * API version: v2.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PolicyHolderCreateModel struct for PolicyHolderCreateModel
type PolicyHolderCreateModel struct {
	// Description not provided.
	Address string `json:"address"`
	// Description not provided.
	AddressLineTwo string `json:"addressLineTwo"`
	// Description not provided.
	City string `json:"city"`
	// Description not provided.
	CompanyName string `json:"companyName"`
	// Description not provided.
	Email string `json:"email"`
	// Description not provided.
	Fax string `json:"fax"`
	// Description not provided.
	Name string `json:"name"`
	// Description not provided.
	Phone string `json:"phone"`
	// Description not provided.
	PostalCode string `json:"postalCode"`
	// Description not provided.
	Province string `json:"province"`
	// Description not provided.
	SfAccountId int32 `json:"sfAccountId"`
	// Description not provided.
	SfCustom map[string]map[string]interface{} `json:"sfCustom"`
	// Description not provided.
	UserId string `json:"userId"`
}
