/*
 * Policy Service
 *
 * Service to interact with Policies and related objects.
 *
 * API version: v2.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InvoiceLineUpdateModel struct for InvoiceLineUpdateModel
type InvoiceLineUpdateModel struct {
	// Description not provided.
	Amount float32 `json:"amount"`
	// Description not provided.
	Details string `json:"details"`
	// Description not provided.
	EntryType string `json:"entryType"`
	// Description not provided.
	InvoiceId string `json:"invoiceId"`
	// Description not provided.
	PolicyHolderId string `json:"policyHolderId"`
	// Description not provided.
	PolicyId string `json:"policyId"`
	// Description not provided.
	SfVersion int32 `json:"sfVersion"`
	// Description not provided.
	TaxAmount float32 `json:"taxAmount"`
}
