/*
 * Policy Service
 *
 * Service to interact with Policies and related objects.
 *
 * API version: v2.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InvoiceLineCreateModel struct for InvoiceLineCreateModel
type InvoiceLineCreateModel struct {
	// Description not provided.
	Amount float32 `json:"amount"`
	// Description not provided.
	Details string `json:"details"`
	// Description not provided.
	EntryType string `json:"entryType"`
	// Description not provided.
	InvoiceId string `json:"invoiceId"`
	// Description not provided.
	PolicyHolderId string `json:"policyHolderId"`
	// Description not provided.
	PolicyId string `json:"policyId"`
	// Description not provided.
	SfAccountId int32 `json:"sfAccountId"`
	// Description not provided.
	TaxAmount float32 `json:"taxAmount"`
}
