/*
 * Policy Service
 *
 * Service to interact with Policies and related objects.
 *
 * API version: v2.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// LapsePolicyResponseModel struct for LapsePolicyResponseModel
type LapsePolicyResponseModel struct {
	Policy PolicyModel `json:"policy"`
}
