/*
 * Policy Service
 *
 * Service to interact with Policies and related objects.
 *
 * API version: v2.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// Metadata struct for Metadata
type Metadata struct {
	// The time in milliseconds the request took on the backend.
	ProcessingTime int64 `json:"processingTime"`
	// A UUID that identifies the request.
	TransactionId string `json:"transactionId"`
}
