/*
 * Policy Service
 *
 * Service to interact with Policies and related objects.
 *
 * API version: v2.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// RenewalLinkModel struct for RenewalLinkModel
type RenewalLinkModel struct {
	// Description not provided.
	ProductIdToPreviousDetailsMap map[string]map[string]interface{} `json:"productIdToPreviousDetailsMap"`
	// Description not provided.
	ProposalId string `json:"proposalId"`
}
