/*
 * Policy Service
 *
 * Service to interact with Policies and related objects.
 *
 * API version: v2.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PaymentAttemptCreateModel struct for PaymentAttemptCreateModel
type PaymentAttemptCreateModel struct {
	// Description not provided.
	InvoiceId string `json:"invoiceId"`
	// Description not provided.
	ProviderResponse string `json:"providerResponse"`
	// Description not provided.
	Sequence int32 `json:"sequence"`
	// Description not provided.
	SfAccountId int32 `json:"sfAccountId"`
	// Description not provided.
	Status string `json:"status"`
}
