/*
 * Policy Service
 *
 * Service to interact with Policies and related objects.
 *
 * API version: v2.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ExceptionModel struct for ExceptionModel
type ExceptionModel struct {
	// Description not provided.
	Code int32 `json:"code"`
	// Description not provided.
	Message string `json:"message"`
	// Description not provided.
	Type string `json:"type"`
}
