/*
 * Policy Service
 *
 * Service to interact with Policies and related objects.
 *
 * API version: v2.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ConvertQuoteResponseModel struct for ConvertQuoteResponseModel
type ConvertQuoteResponseModel struct {
	Bundle PolicyBundleModel `json:"bundle"`
	Policies []PolicyModel `json:"policies"`
}
