/*
 * Policy Service
 *
 * Service to interact with Policies and related objects.
 *
 * API version: v2.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PolicyHolderNoteCreateModel struct for PolicyHolderNoteCreateModel
type PolicyHolderNoteCreateModel struct {
	// Description not provided.
	CreatedBy string `json:"createdBy"`
	// Description not provided.
	Note string `json:"note"`
	// Description not provided.
	PolicyHolderId string `json:"policyHolderId"`
	// Description not provided.
	SfAccountId int32 `json:"sfAccountId"`
}
