/*
 * Policy Service
 *
 * Service to interact with Policies and related objects.
 *
 * API version: v2.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PaymentAttemptUpdateModel struct for PaymentAttemptUpdateModel
type PaymentAttemptUpdateModel struct {
	// Description not provided.
	InvoiceId string `json:"invoiceId"`
	// Description not provided.
	ProviderResponse string `json:"providerResponse"`
	// Description not provided.
	Sequence int32 `json:"sequence"`
	// Description not provided.
	SfVersion int32 `json:"sfVersion"`
	// Description not provided.
	Status string `json:"status"`
}
