/*
 * Policy Service
 *
 * Service to interact with Policies and related objects.
 *
 * API version: v2.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PolicyBundleCreateModel struct for PolicyBundleCreateModel
type PolicyBundleCreateModel struct {
	// Description not provided.
	InvoiceId string `json:"invoiceId"`
	// Description not provided.
	SfAccountId int32 `json:"sfAccountId"`
	// Description not provided.
	Status string `json:"status"`
	// Description not provided.
	Type string `json:"type"`
}
