/*
 * Policy Service
 *
 * Service to interact with Policies and related objects.
 *
 * API version: v2.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PolicyEndorseModel struct for PolicyEndorseModel
type PolicyEndorseModel struct {
	// Description not provided.
	Config string `json:"config"`
}
