/*
 * Policy Service
 *
 * Service to interact with Policies and related objects.
 *
 * API version: v2.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PolicyTerminateModel struct for PolicyTerminateModel
type PolicyTerminateModel struct {
	// Description not provided.
	Note string `json:"note"`
	Refund RefundModel `json:"refund"`
}
