/*
 * Policy Service
 *
 * Service to interact with Policies and related objects.
 *
 * API version: v2.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PolicyHolderModel struct for PolicyHolderModel
type PolicyHolderModel struct {
	// Description not provided.
	Address string `json:"address"`
	// Description not provided.
	AddressLineTwo string `json:"addressLineTwo"`
	// Description not provided.
	City string `json:"city"`
	// Description not provided.
	CompanyName string `json:"companyName"`
	// Description not provided.
	Email string `json:"email"`
	// Description not provided.
	Fax string `json:"fax"`
	// Description not provided.
	Name string `json:"name"`
	// Description not provided.
	Phone string `json:"phone"`
	// Description not provided.
	PostalCode string `json:"postalCode"`
	// Description not provided.
	Province string `json:"province"`
	// Description not provided.
	SfCustom map[string]map[string]interface{} `json:"sfCustom"`
	// Description not provided.
	UserId string `json:"userId"`
	// The id of the entity.
	Id string `json:"id"`
	// ID of account in IAM hierarchy.
	SfAccountId int32 `json:"sfAccountId,omitempty"`
	// The timestamp of when the entity was created.
	SfCreated string `json:"sfCreated"`
	// User ID of entity owner.
	SfOwnerId string `json:"sfOwnerId,omitempty"`
	// Path of entity in IAM hierarchy.
	SfPath string `json:"sfPath,omitempty"`
	// ID of tenant that entity belongs to.
	SfTenantId int32 `json:"sfTenantId,omitempty"`
	// The timestamp of when the entity was last updated.
	SfUpdated string `json:"sfUpdated"`
	// The current version of the entity.
	SfVersion int32 `json:"sfVersion"`
}
