/*
 * Policy Service
 *
 * Service to interact with Policies and related objects.
 *
 * API version: v2.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PolicyBundleUpdateModel struct for PolicyBundleUpdateModel
type PolicyBundleUpdateModel struct {
	// Description not provided.
	InvoiceId string `json:"invoiceId"`
	// Description not provided.
	SfVersion int32 `json:"sfVersion"`
	// Description not provided.
	Status string `json:"status"`
	// Description not provided.
	Type string `json:"type"`
}
