/*
 * Policy Service
 *
 * Service to interact with Policies and related objects.
 *
 * API version: v2.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PolicyBundleModel struct for PolicyBundleModel
type PolicyBundleModel struct {
	// Description not provided.
	InvoiceId string `json:"invoiceId"`
	// Description not provided.
	Status string `json:"status"`
	// Description not provided.
	Type string `json:"type"`
	// The id of the entity.
	Id string `json:"id"`
	// ID of account in IAM hierarchy.
	SfAccountId int32 `json:"sfAccountId,omitempty"`
	// The timestamp of when the entity was created.
	SfCreated string `json:"sfCreated"`
	// User ID of entity owner.
	SfOwnerId string `json:"sfOwnerId,omitempty"`
	// Path of entity in IAM hierarchy.
	SfPath string `json:"sfPath,omitempty"`
	// ID of tenant that entity belongs to.
	SfTenantId int32 `json:"sfTenantId,omitempty"`
	// The timestamp of when the entity was last updated.
	SfUpdated string `json:"sfUpdated"`
	// The current version of the entity.
	SfVersion int32 `json:"sfVersion"`
}
