/*
 * Policy Service
 *
 * Service to interact with Policies and related objects.
 *
 * API version: v2.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// AmendPolicyResponseModel struct for AmendPolicyResponseModel
type AmendPolicyResponseModel struct {
	Bundle PolicyBundleModel `json:"bundle"`
	Policy PolicyModel `json:"policy"`
}
