/*
 * Policy Service
 *
 * Service to interact with Policies and related objects.
 *
 * API version: v2.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// SetInvoiceLineOwnerModel struct for SetInvoiceLineOwnerModel
type SetInvoiceLineOwnerModel struct {
	// Description not provided.
	OwnerId string `json:"ownerId"`
}
