/*
 * Policy Service
 *
 * Service to interact with Policies and related objects.
 *
 * API version: v2.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PolicyLapseModel struct for PolicyLapseModel
type PolicyLapseModel struct {
	// Description not provided.
	Note string `json:"note"`
}
